server:
  port: 1113
spring:
  application:
    name: eureka-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
resilience4j:
  ratelimiter:
    limiters:
      rlA:
        # 每次处理几个请求
        limit-for-period: 1
        # 刷新的时间
        limit-refresh-period: 1000
        # 冷却时间
        timeout-duration: 1000
