

server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

resilience4j:
  retry:
    # 表示retry的优先级
    retry-aspect-order: 399
    backends:
      retryA:
        # 重试的次数
        maxRetryAttempts: 5
        # 重试等待时间
        waitDuration: 500
        # 间隔乘数
        exponentialBackoffMultiplier: 1.1
        retryExceptions:
          - java.lang.RuntimeException
spring:
  application:
    name: resilience4j-web
