spring:
  rabbitmq:
    host: 192.168.37.128
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        xsc-input:
          destination: delay-msg
#          # 添加分组消息只被一个实例消费
          group: g1
#          consumer:
#            # 开启分区(消费者上配置)
#            partitioned: true
        xsc-output:
          destination: delay-msg
      # rabbit 消息延迟
      rabbit:
        bindings:
          xsc-input:
            consumer:
              # 开启消息延迟
              delayed-exchange: true
          xsc-output:
            producer:
              # 开启消息延迟
              delayed-exchange: true
#          group: g1
#          producer:
#            # 消费端的节点数量(生产者上配置)
#            partitionCount: 2
#            # 根据实际的输出消息规则来配置SpEL来生成合适的分区键(生产者上配置)
#            partitionKeyExpression: payload
#      # 消费者实例个数(消费者上配置)
#      instance-count: 2
#      # 当前实例的下标(消费者上配置)
#      instance-index: 0
