spring:
  rabbitmq:
    host: 192.168.37.128
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        xsc-input:
          destination: xsc-topic
        xsc-output:
          destination: xsc-topic
