spring:
  rabbitmq:
    host: 192.168.37.128
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        xsc-input:
          destination: xsc-topic
          # 添加分组消息只被一个实例消费
          group: g1
        xsc-output:
          destination: xsc-topic
          group: g1
